# Generated by Django 2.1.7 on 2019-02-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ava_profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_offical',
            field=models.BooleanField(default=False),
        ),
    ]
